version: "3.8"

services:
  mdcx:
    image: stainless403/mdcx-builtin-gui-base:v2-20260324-dev
    container_name: mdcx
    restart: unless-stopped
    ports:
      - "5800:5800"   # Web访问端口
      - "5900:5900"
    volumes:
      - /home/mdcx/data:/config                # 容器系统数据
      - /home/mdcx/mdcx-config:/mdcx-config    # 配置文件目录
      - /home/mdcx/mdcx-config/MDCx.config:/app/MDCx.config  # 配置文件目录标记文件
      - /home/mdcx/logs:/app/Log               # 日志目录
      - /mnt/smartstrm/strm:/strm             # 影片目录
    environment:
      TZ: Asia/Shanghai
      DISPLAY_WIDTH: 1200
      DISPLAY_HEIGHT: 750
      VNC_PASSWORD: "密码"   # 查看密码，可自行设置
      USER_ID: "${UID}"  # 运行应用的用户ID
      GROUP_ID: "${GID}" # 运行应用的用户组ID