services:
    embyserver:
        image: emby/embyserver:latest
        container_name: embyserver
        network_mode: bridge
        # privileged: true  # <--- 取消注释，赋予特权模式
        environment:
            - UID=0
            - GID=0
            - GIDLIST=0
            - TZ=Asia/Shanghai
        volumes:
            - /home/embyserver/config:/config
            - /mnt/fnos_samba:/fnos
            - /mnt/nas_samba:/nas
            - /mnt/smartstrm/strm:/strm
            - /mnt/smartstrm/StrmAssistant:/StrmAssistant
            #- /home/embyserver/embycrack/Emby.Web.dll:/system/Emby.Web.dll
            #- /home/embyserver/embycrack/Emby.Server.Implementations.dll:/system/Emby.Server.Implementations.dll
            #- /home/embyserver/embycrack/dashboard-ui/embypremiere/embypremiere.js:/system/dashboard-ui/embypremiere/embypremiere.js
            #- /home/embyserver/embycrack/dashboard-ui/modules/emby-apiclient/connectionmanager.js:/system/dashboard-ui/modules/emby-apiclient/connectionmanager.js
        ports:
            - 8096:8096
        devices:
            - /dev/dri:/dev/dri
        restart: unless-stopped