version: "3.8"
services:
  subconverter-extended:
    container_name: "subconverter"
    image: "aethersailor/subconverter-extended:latest"
    ports:
      - "25500:25500/tcp"
    restart: unless-stopped
    volumes:
      - /home/SubConverter-Extended/base/pref.toml:/base/pref.toml